### ISSUE TITLE
Add the private region eu-fr2

### ISSUE THREAD

**Issue by zivnevo** [np-guard/cloud-resource-collector#293]

**Comment by zivnevo** [comment]
Note: this is a private IBM region - not everyone can access it.
Users without the proper credentials will get a `user does not have access` error.
Hence, we need to skip this region (and other private regions) if the user doesn't specify a region.
To collect resources from private regions, user will have to specify these regions explicitly using the `-r` flag.

**Comment by kyorav** [comment]
Also, I think we should *not* add this region to the list of regions, i.e. when users ask to see the list of regions it will not appear. We kind of need to hide this because it is a bespoke feature for BNPP only.
